changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - Victor Hang
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - breaking-change
    - title: Features 🎉
      labels:
        - Semver-Minor
        - enhancement
    - title: Enhancements ✨
      labels:
        - '*'
      exclude:
        labels:
          - dependencies
    - title: 👒 Dependencies
      labels:
        - dependencies
