version: 2
before:
  hooks:
    - go mod tidy
builds:
  - binary: ytui
    main: ./
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
      - arm
    ldflags:
      - -s -w -X github.com/Banh-Canh/ytui/cmd.version=v{{.Version}}
archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_v{{- .Version }}_ {{- title .Os }}_ {{- if eq .Arch "amd64" }}x86_64 {{- else if eq .Arch "386" }}i386 {{- else }}{{ .Arch }}{{ end }} {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - docs/*
aurs:
  - name: 'ytui-bin'
    homepage: 'https://github.com/banh-canh/ytui'
    description: 'ytui is a TUI tool that allows users to query videos on youtube and play them in their local player.'
    maintainers:
      - 'Victor Hang <vhvictorhang@gmail.com>'
    license: 'MIT'
    private_key: '{{ .Env.AUR_KEY }}'
    git_url: 'ssh://aur@aur.archlinux.org/ytui-bin.git'
    commit_author:
      name: 'Victor Hang'
      email: 'vhvictorhang@gmail.com'
    skip_upload: auto
brews:
  - name: 'ytui'
    homepage: https://github.com/banh-can/ytui
    description: 'An interactive Kubernetes log viewer for your terminal.'
    directory: Formula
    commit_author:
      name: 'Victor Hang'
      email: 'vhvictorhang@gmail.com'
    commit_msg_template: 'chore: Brew formula update for {{ .ProjectName }} version {{ .Tag }}'
    repository:
      owner: banh-canh
      name: ytui-tap
      branch: main
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
